checks run U.T now, WIP EKS detector
lumigo-io/opentelemetry-python-distro pull request #146
Opened 2022-10-30 13:17 UTC by GuyMoses

2022-10-30 15:22 UTC, nirLumigo requested changes
Nice! :)

2022-10-30 15:22 UTC, nirLumigo commented on src/lumigo_opentelemetry/__init__.py
> +    # Suppress spurious warnings when the application is not running on EKS
Don't you need to add `if` to verify we're not inside an EKS?

2022-10-30 15:22 UTC, nirLumigo commented on src/test/unit/resources/eks_utils.py
> +get_cluster_info = f"""{{
Usually when importing a const it's upper case and a function is a lower case
```suggestion
GET_CLUSTER_INFO = f"""{{
```

2022-10-30 15:22 UTC, nirLumigo commented on src/test/unit/resources/eks_utils.py
> +container_id_text = f"""14:name=systemd:/docker/{MockEksResourceAttributes[ResourceAttributes.CONTAINER_ID]}
```suggestion
CONTAINER_ID_TEXT = f"""14:name=systemd:/docker/{MockEksResourceAttributes[ResourceAttributes.CONTAINER_ID]}
```

2022-10-30 15:22 UTC, nirLumigo commented on src/test/unit/resources/test_detectors.py
> +    assert isinstance(resource.attributes[ResourceAttributes.CONTAINER_ID], str)
Why not add
`assert len(resource.attributes[ResourceAttributes. CONTAINER_ID]) > 1`
as well?

2022-10-30 15:23 UTC, nirLumigo approved these changes

2022-11-02 14:18 UTC, mmanciop approved these changes

2022-12-07 10:00 UTC, merged