RD 13495 opentelemetry python contrib version
lumigo-io/opentelemetry-python-distro pull request #870
Opened 2024-08-28 10:11 UTC by eugene-lumigo

- **Version 1.26.0/0.47b0**
- **Version 1.26.0/0.47b0**
- **Revert "Version 1.26.0/0.47b0"**

2024-08-29 12:24 UTC, sagivoululumigo requested changes
Remember to update the readme for supported runtimes.

Note: Don't manually edit the supported versions table, I think the automated version tester should take care of that

2024-09-01 10:46 UTC, GuyMoses requested changes
in the `README.md` file please state exactly when we deprecated python3.7 and state exactly the last known version to be supporting python3.7

2024-09-10 09:28 UTC, sagivoululumigo commented on .github/workflows/version-testing.yml
> -          path: versions_artifacts/3.7
Why remove this step?

2024-09-10 09:31 UTC, sagivoululumigo commented on src/lumigo_opentelemetry/__init__.py
> +        return {}
Put this inside a try catch block, so if in python 3.13 they change the interface of `sys.version_info` then the tracer won't crash.

If this block fails just log a warning saying that we failed to verify the python version.

2024-09-10 09:32 UTC, sagivoululumigo commented on src/lumigo_opentelemetry/instrumentations/fastapi/parsers/__init__.py
> +    ) -> None:
Why?

2024-09-10 09:34 UTC, sagivoululumigo reviewed
Overall good, left small comments

2024-09-11 09:45 UTC, eugene-lumigo commented on .github/workflows/version-testing.yml
> -          path: versions_artifacts/3.7
We discussed this

2024-09-11 10:02 UTC, sagivoululumigo commented on src/lumigo_opentelemetry/__init__.py
> +        return {}
Don't only check for an `AttributeError` check for any error.
This is a fail safe for unexpected errors, so don't catch only one expected error...

2024-09-11 10:02 UTC, sagivoululumigo commented on .github/workflows/version-testing.yml
> -          path: versions_artifacts/3.7
OK

2024-09-11 13:14 UTC, sagivoululumigo commented on src/lumigo_opentelemetry/__init__.py
> +        return {}
Approved the fix

2024-09-11 13:15 UTC, sagivoululumigo commented on src/lumigo_opentelemetry/instrumentations/fastapi/parsers/__init__.py
> +    ) -> None:
Understood

2024-09-11 13:15 UTC, sagivoululumigo approved these changes
Approved

2024-09-12 07:23 UTC, GuyMoses approved these changes

2024-09-12 07:23 UTC, merged