RD-14031-Pure-python-script-instrumentation-bad-experience
lumigo-io/opentelemetry-python-distro pull request #963
Opened 2024-11-26 08:39 UTC by eugene-lumigo

2024-11-26 09:10 UTC, sagivoululumigo commented on README.md
> +### Decorator-based activation
I wouldn't call the `Decorator based activation`, this is useful for instrumenting simple scripts (or just scripts).
Why not call it `Script instrumentation`?
@lir-lumigo WDYT?

2024-11-26 09:11 UTC, sagivoululumigo commented on README.md
> +### Decorator-based activation
BTW this should be a sub-section of the manual instrumentation

2024-11-26 09:13 UTC, sagivoululumigo commented on README.md
> +For simple Python scripts that are not built around Lumigo or OpenTelemetry-instrumented libraries, you can use the `@lumigo_wrapped` decorator for activation. This approach is especially useful for
You need to first mention that by default if using the autowrapping or manual activation then the script will be instrumented, but there are limitations such as:
* The last spans might be lost if the script ends before they are sent
* If no outbound requests are made (For example if the code crashes before the first call is made) then the script run wont generate any traces in lumigo

2024-11-26 09:14 UTC, sagivoululumigo commented on README.md
> +The `@lumigo_wrapped` decorator is a convenient way to add OpenTelemetry tracing to functions in scripts that are not using libraries or frameworks instrumented by Lumigo or OpenTelemetry.
I would call it lumigo tracing, no need to talk about the underlying otel

2024-11-26 09:17 UTC, sagivoululumigo commented on README.md
> +This approach is particularly useful for standalone Python scripts or cron jobs where use of the [OpenTelemetry SDK](https://opentelemetry.io/docs/languages/java/) is not feasible.
Why are you referencing java here?

2024-11-26 09:19 UTC, sagivoululumigo requested changes
See notes + add a unit test for the lumigo wrapped

2024-12-01 09:13 UTC, lir-lumigo commented on README.md
> +2. **No traces generated without outbound requests**: If no outbound requests are made (e.g., the code crashes before the first call is executed), the script run will not generate any traces in Lumig
@eugene-lumigo does this limitation also apply when using the wrapper?

2024-12-01 09:17 UTC, lir-lumigo commented on README.md
> +##### Script instrumentation
```suggestion
#### Script instrumentation
```
Trying to reduce the depth of titles here

2024-12-01 09:17 UTC, lir-lumigo commented on README.md
> +#### Limitations
Do these limitations apply to all activation methods?

2024-12-01 09:17 UTC, lir-lumigo commented on README.md
> +This approach is particularly useful for standalone Python scripts or cron jobs where use of the [OpenTelemetry SDK](https://opentelemetry.io/docs/languages/python/) is not feasible.
@eugene-lumigo I think we can remove this line

2024-12-04 08:15 UTC, merged